## $\bullet$ Genotype Data

In [31]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer

In [32]:
fgenotype = "../data/genotype/genotype_matrix.xlsx"

In [33]:
#
# Somehow there are multiple sheets, that I actually could see in libreCalc 
#
excel_p = pd.ExcelFile(fgenotype)
excel_p.sheet_names

['WinSTAT Commands', 'WinSTAT Trigger', 'Tabelle2']

In [34]:
#
# Just Select with sheet_name
#
df_g = pd.read_excel(excel_p, sheet_name="Tabelle2")
df_g.head(6)

,Marker,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,Position im Genom,2.3,4,6.3,6.3,8.6,8.6,10.4,15.4,15.4,...,138.6,138.6,140.8,142.6,142.6,144.4,146.4,146.4,146.4,148.2
1,Elter A,A,A,A,A,A,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
2,Elter B,B,B,B,B,B,B,B,B,B,...,B,B,B,B,B,B,B,B,B,B
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nachkommenschaft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,HEB_01_001,B,B,B,B,B,B,B,A,A,...,A,A,A,A,A,A,A,A,A,A

### Data Processing

In [35]:
#
# export locational df (position in genome)
#
df_loc = pd.DataFrame(data = {"Marker" : df_g.columns[1:],
                              "Chr"    : [2 for i in range(len(df_g.columns[1:]))],
                              "Pos"    : df_g.iloc[0, 1:]})
df_loc.to_csv("../data/genotype/genotype_location.csv", index=False)
df_loc.head()

                        Marker  Chr  Pos
SCRI_RS_136200  SCRI_RS_136200    2  2.3
SCRI_RS_156845  SCRI_RS_156845    2    4
SCRI_RS_133377  SCRI_RS_133377    2  6.3
SCRI_RS_190048  SCRI_RS_190048    2  6.3
BOPA2_12_31497  BOPA2_12_31497    2  8.6

In [36]:
#
# Remove irrelevant rows from df, replace 'u' with nan
# (Somehow, this is the way it is encoded) and make 
# genotypes numeric. 
#
df_nan = df_g.iloc[5:, :]
df_nan.index = [i for i in range(len(df_nan))]
df_nan.replace('u', np.float64("nan"), inplace=True)
df_nan.replace("A", 0, inplace=True)
df_nan.replace("h", 1, inplace=True)
df_nan.replace("B", 2, inplace=True)

#
# Initially, I thought GAPIT handles nan values internally,
# thats why also saved the nan df. 
#
df_nan.to_csv("../data/genotype/genotype_matrix_nan.csv", index=False)
df_nan

/tmp/ipykernel_3191/575769222.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan.replace('u', np.float64("nan"), inplace=True)
/tmp/ipykernel_3191/575769222.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan.replace("A", 0, inplace=True)
/tmp/ipykernel_3191/575769222.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan.replace("h", 1, inplace=True)
/tmp/ipykernel_3191/575769222.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_nan.replace("B", 2, inplace=True)
/tmp/ipykernel_3191/575769222.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan.replace("B", 2, inplace=True)

,Marker,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2,2.0,2,2,2,2,2,0,0,...,0,0.0,0,0,0,0,0,0,0,0
1,HEB_01_003,2,2.0,2,2,2,2,2,1,2,...,0,0.0,0,0,0,0,0,0,0,0
2,HEB_01_004,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,2,2,2,2
3,HEB_01_005,2,2.0,2,2,2,2,2,1,1,...,0,0.0,0,0,0,0,0,0,0,0
4,HEB_01_013,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,HEB_10_176,2,2.0,2,2,2,2,2,2,2,...,0,0.0,2,2,2,2,2,2,2,2
116,HEB_10_182,0,NaN,0,0,0,0,0,0,0,...,1,1.0,2,2,2,2,2,2,2,2
117,HEB_10_184,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
118,HEB_10_187,2,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
119,HEB_10_190,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2

In [37]:
#
# NaN values must be handled in the preprocessing step, but you cannot
# just add a mean genotype, you must use different approaches. My first
# idea was to use the most frequent genotype in the markers column (this
# is called the mode imputation).
#
impute_mode = SimpleImputer(strategy="most_frequent")
df_mode = pd.concat([df_nan.iloc[:, 0], 
                     pd.DataFrame(columns = df_nan.columns[1:],                                 # some tmp df
                                  data = impute_mode.fit_transform(X = df_nan.iloc[:, 1:]))],
                     axis=1)
df_mode.to_csv("../data/genotype/genotype_matrix_mode.csv", index=False)
df_mode

,Marker,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,HEB_01_003,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,HEB_01_004,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0
3,HEB_01_005,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,HEB_01_013,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,HEB_10_176,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
116,HEB_10_182,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
117,HEB_10_184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
118,HEB_10_187,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
119,HEB_10_190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [38]:
#
# After some reasearch, I fount that KNN impute followed
# by an int cast is a standard approch. 
#
impute_knn = KNNImputer()
df_mode = pd.concat([df_nan.iloc[:, 0], 
                     pd.DataFrame(columns = df_nan.columns[1:],                                 # some tmp df
                                  data = impute_knn.fit_transform(X = df_nan.iloc[:, 1:])).round(0)],
                     axis=1)
df_mode.to_csv("../data/genotype/genotype_matrix_knn.csv", index=False)
df_mode

,Marker,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,HEB_01_003,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,HEB_01_004,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0
3,HEB_01_005,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,HEB_01_013,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,HEB_10_176,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
116,HEB_10_182,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
117,HEB_10_184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
118,HEB_10_187,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
119,HEB_10_190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0