## $\bullet$ Phenotype Data

In [30]:
import pandas as pd
import numpy as np

In [31]:
fphenotype = "../data/phenotype/phenotype_matrix.xlsx"

In [32]:
#
# only a single sheet 
#
excel_p = pd.ExcelFile(fphenotype)
excel_p.sheet_names

['Tabelle1']

In [33]:
df_p = pd.read_excel(excel_p)
df_p.head()

     Genotype  HEA    TGW   HEI   RIP   PM
0  HEB_01_001   62  53.63  53.0  35.0  7.0
1  HEB_01_003   67  57.62  58.0  34.0  5.0
2  HEB_01_004   57  52.15  74.0  40.0  1.0
3  HEB_01_005   69  54.16  60.0  34.0  6.0
4  HEB_01_013   64  51.40  60.0  34.0  1.0

### Data Processing

In [34]:
#
# make all float
#
df_p.iloc[:, 1:] = df_p.iloc[:, 1:].astype(np.float64)
df_p.iloc[:20,:]

/tmp/ipykernel_3231/1389494488.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      62.0
1      67.0
2      57.0
3      69.0
4      64.0
       ...
115    78.0
116    55.0
117    62.0
118    60.0
119    64.0
Name: HEA, Length: 120, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_p.iloc[:, 1:] = df_p.iloc[:, 1:].astype(np.float64)

      Genotype   HEA    TGW   HEI   RIP   PM
0   HEB_01_001  62.0  53.63  53.0  35.0  7.0
1   HEB_01_003  67.0  57.62  58.0  34.0  5.0
2   HEB_01_004  57.0  52.15  74.0  40.0  1.0
3   HEB_01_005  69.0  54.16  60.0  34.0  6.0
4   HEB_01_013  64.0  51.40  60.0  34.0  1.0
5   HEB_01_021  81.0  56.44  58.0  31.0  1.0
6   HEB_01_022  95.0  53.27   NaN   NaN  NaN
7   HEB_01_023  67.0  59.55  55.0  35.0  7.0
8   HEB_01_025  53.0  59.10  40.0  42.0  1.0
9   HEB_01_030  69.0  54.53  62.0  36.0  7.0
10  HEB_01_031  60.0  46.84  37.0  30.0  NaN
11  HEB_01_032  64.0  58.80  74.0  34.0  1.0
12  HEB_01_033  60.0  58.79  57.0  37.0  1.0
13  HEB_01_038  69.0  44.84  60.0  30.0  1.0
14  HEB_01_041  71.0  51.90  46.0  31.0  1.0
15  HEB_01_042  69.0  50.54  53.0  33.0  NaN
16  HEB_01_047  69.0  48.01  54.0  33.0  1.0
17  HEB_01_050  71.0  47.58  54.0  32.0  1.0
18  HEB_01_053  74.0  49.09  47.0  29.0  6.0
19  HEB_01_055  71.0  51.18  45.0  32.0  NaN

In [35]:
#
# Since one is interested in the significant markers, one can clearly 
# replace NaN's with the colums mean. Since the number of samples is not 
# not to great, dropping might has a noticable statistical effect here: 
# -> df_p.dropna(inplace=True) | alternative
#
for i in range(1, len(df_p.columns)):
    df_p.iloc[:, i].replace(
        to_replace=np.float64("nan"), 
        value=df_p.iloc[:, i].mean(skipna=True), 
        inplace=True
    )
df_p.iloc[:20,:]

/tmp/ipykernel_3231/3052237685.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_p.iloc[:, i].replace(

      Genotype   HEA    TGW        HEI        RIP        PM
0   HEB_01_001  62.0  53.63  53.000000  35.000000  7.000000
1   HEB_01_003  67.0  57.62  58.000000  34.000000  5.000000
2   HEB_01_004  57.0  52.15  74.000000  40.000000  1.000000
3   HEB_01_005  69.0  54.16  60.000000  34.000000  6.000000
4   HEB_01_013  64.0  51.40  60.000000  34.000000  1.000000
5   HEB_01_021  81.0  56.44  58.000000  31.000000  1.000000
6   HEB_01_022  95.0  53.27  59.621849  32.789916  3.155963
7   HEB_01_023  67.0  59.55  55.000000  35.000000  7.000000
8   HEB_01_025  53.0  59.10  40.000000  42.000000  1.000000
9   HEB_01_030  69.0  54.53  62.000000  36.000000  7.000000
10  HEB_01_031  60.0  46.84  37.000000  30.000000  3.155963
11  HEB_01_032  64.0  58.80  74.000000  34.000000  1.000000
12  HEB_01_033  60.0  58.79  57.000000  37.000000  1.000000
13  HEB_01_038  69.0  44.84  60.000000  30.000000  1.000000
14  HEB_01_041  71.0  51.90  46.000000  31.000000  1.000000
15  HEB_01_042  69.0  50.54  53.000000  33.000000  3.155963
16  HEB_01_047  69.0  48.01  54.000000  33.000000  1.000000
17  HEB_01_050  71.0  47.58  54.000000  32.000000  1.000000
18  HEB_01_053  74.0  49.09  47.000000  29.000000  6.000000
19  HEB_01_055  71.0  51.18  45.000000  32.000000  3.155963

In [36]:
#
# export
#
df_p.to_csv("../data/phenotype/phenotype_matrix.csv", index=False)