- Just add the ratio of the sprout weight of total mass (transformation)  

    $Y = \frac{X_1}{X_1 + X_2}$        proportion of sprout mass in (total) biomass

- Where  

    $X_1 $ is sprout weight  
    $X_2 $ is root weight

In [ ]:
import pandas as pd

In [ ]:
path_data = "../data/dry_weight/pflanzen.tsv"

In [17]:
df = pd.read_csv(path_data, sep="\t")
df.head()

   Nr  Spross  Wurzel
0   1    13.3     8.8
1   2    27.1     9.9
2   3     0.9     0.3
3   4    10.0     5.5
4   5    11.8     4.2

In [18]:
ratio = df["Spross"] / (df["Spross"] + df["Wurzel"])
df_ratio = pd.DataFrame(ratio, columns=["ratio"])
df = pd.concat([df, df_ratio], axis=1)
df.head()

   Nr  Spross  Wurzel     ratio
0   1    13.3     8.8  0.601810
1   2    27.1     9.9  0.732432
2   3     0.9     0.3  0.750000
3   4    10.0     5.5  0.645161
4   5    11.8     4.2  0.737500

In [19]:
df.to_csv("../data/dry_weight/pflanzen_incl_ratio.csv",index=False)